name: ci-golang-workflows-dev
##on: [push]
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

